
version: '3.8'

services:
  image-storage:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    environment:
      - BASE_PATH=images
      - MAX_SIZE_MB=10
      - ALLOWED_TYPES=image/jpeg,image/png,image/gif,image/webp
      - SESSION_SECRET=change-this-secure-key-in-production
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
